/* SPDX-License-Identifier: GPL-3.0-only */
static unsigned cb_action,cb_nested;
static void cb_lcd(void);
#define UI_ASYNC_LCD 1
#define UI_LCD_SYNC_HOOK cb_lcd
#define D8_SOURCE_EQ_NO_MAIN 1
#include "native_source_equivalence_test.c"
#include "../firmware/src/native_migration_capture_binding.c"
#include "../firmware/src/native_migration_execute.c"
static uint32_t expected[17],g;
static unsigned erases,programs,scratch_checks;
static void cb_lcd(void){unsigned a=cb_action;cb_action=0;if(a==1)trk[7].p[P_LEVEL]^=1;else if(a==2)settings.lowcut^=1;else if(a==3)usb.config=0;else if(a==4)d8_capture_store_changed();else if(a==5){uint32_t other=777;cb_nested=d8cb_begin(&other);CHECK(other==777);}else if(a==6)ed_capture.token++;}
static void retained(unsigned choice,unsigned full){d8cb_cancel();d8mx_cancel();CHECK(sv_build("tests/fixtures/projects/fun1.bin",7,choice,0));sv_end();begin_capture(full);CHECK(!status());scan();uint8_t bytes[256];for(unsigned role=0;role<(full?17:12);role++)for(unsigned off=0;off<edc_length(role);off+=256){unsigned n=edc_length(role)-off;if(n>256)n=256;CHECK(reply_bytes(bytes,role,off,n));}op(5);CHECK(!status());scan();CHECK(ed_capture.phase==4&&ed_capture.active);memcpy(expected,ed_capture.crc,sizeof expected);g=0;cb_action=cb_nested=erases=programs=scratch_checks=0;}
static int proposal(unsigned choice){int rc=d8cb_begin(&g);if(rc)return rc;sv_g=g;CHECK(!ed_capture.active&&!memcmp(expected,d8cb.crc,sizeof expected));for(unsigned off=0;off<D8POOL_BYTES;off+=256)CHECK(d8cb_receive(g,off,sv_plan+off,256)==D8CB_OK);d8sv_io io={NULL,sv_rd,sv_valid};rc=d8cb_source_begin(g,&io,choice);unsigned n=0;while(rc==D8SV_MORE){rc=d8cb_source_step();CHECK(++n<1000);}return rc;}
static int permit(void*c,uint32_t id){(void)c;d8mp_workspace*w=main_migration_workspace(id);if(!w)return 0;uint32_t before=d8p1_crc32(&w->stage,sizeof w->stage);int okay=d8cb_metadata_valid(id);CHECK(before==d8p1_crc32(&w->stage,sizeof w->stage));scratch_checks++;return okay&&d8mx.plan_crc==d8cb.plan_crc&&!memcmp(d8mx.original,d8cb.crc,sizeof d8mx.original);}
static int erase(void*c,uint32_t a){(void)c;CHECK(permit(NULL,g)&&a%4096==0);memset(nor+a,255,4096);erases++;return 0;}
static int program(void*c,uint32_t a,const void*p,uint32_t n){(void)c;CHECK(permit(NULL,g)&&n<=256);for(unsigned i=0;i<n;i++)nor[a+i]&=((const uint8_t*)p)[i];programs++;return 0;}
static void end(void){d8cb_cancel();d8mx_cancel();CHECK(!migration_owner&&!writes);}
int main(void){
 for(unsigned choice=0;choice<2;choice++){retained(choice,1);CHECK(proposal(choice)==D8SV_COMPLETE&&d8cb_seal(g)==D8CB_OK&&d8mp.phase==1);d8mx_io io={NULL,sv_rd,erase,program,permit};CHECK(d8mx_begin(g,&io,d8cb.crc)==D8MX_MORE&&d8mp.phase==4);int rc=D8MX_MORE;unsigned n=0;while(rc==D8MX_MORE){rc=d8mx_step();CHECK(++n<3000);}CHECK(rc==D8MX_COMPLETE&&erases==10&&programs==170&&scratch_checks>1000);for(unsigned b=0;b<5;b++)CHECK(!memcmp(nor+d8pool_mapped_address(b),sv_plan+b*D8POOL_BLOCK,D8POOL_BLOCK));for(unsigned a=0;a<sizeof nor;a++){int changed=0;for(unsigned b=0;b<5;b++)if(a>=d8pool_mapped_address(b)&&a<d8pool_mapped_address(b)+D8POOL_BLOCK)changed=1;if(!changed)CHECK(nor[a]==baseline[a]);}end();}
 uint32_t untouched=4321;retained(D8SV_CURRENT,0);CHECK(d8cb_begin(&untouched)==D8CB_CHANGED&&untouched==4321&&!migration_owner);end();retained(D8SV_CURRENT,1);ed_capture.phase=2;CHECK(d8cb_begin(&untouched)==D8CB_CHANGED&&untouched==4321&&!migration_owner);end();
 for(unsigned role=12;role<17;role++){retained(D8SV_CURRENT,1);if(role==12)trk[7].p[P_LEVEL]^=1;else if(role==13)settings.lowcut^=1;else if(role<16)((uint8_t*)&up_bank[role-14])[50]^=1;else ((uint8_t*)&upf)[50]^=1;CHECK(d8cb_begin(&untouched)==D8CB_CHANGED&&untouched==4321&&!migration_owner);end();}
 for(unsigned a=1;a<=6;a++){retained(D8SV_CURRENT,1);cb_action=a;int rc=d8cb_begin(&untouched);if(a==5){CHECK(rc==D8CB_OK&&cb_nested==D8CB_BUSY);untouched=4321;}else CHECK(rc==D8CB_CHANGED&&untouched==4321&&!migration_owner);end();}
 retained(D8SV_CURRENT,1);CHECK(d8cb_begin(&g)==D8CB_OK);sv_g=g;trk[7].p[P_LEVEL]^=1;memset(&sv_state,0,sizeof sv_state);project_capture(&sv_state.project);size_t z=0;CHECK(d8p1_project_encode(out,sizeof out,&z,&sv_state));d8pool pool={NULL,sv_pr,sv_pe,sv_pp,stop};CHECK(!d8pool_save(&pool,3,out,z,7));d8pool_index index;CHECK(!d8pool_inventory(&pool,&index));unsigned used=0;for(unsigned o=0;o<4;o++)if(index.present&(1u<<o))used|=1u<<index.object[o].block;for(unsigned b=0;b<5;b++)if(!(used&(1u<<b)))memset(sv_plan+b*D8POOL_BLOCK,255,D8POOL_BLOCK);for(unsigned off=0;off<D8POOL_BYTES;off+=256)CHECK(d8cb_receive(g,off,sv_plan+off,256)==D8CB_OK);d8sv_io sio={NULL,sv_rd,sv_valid};int rc=d8cb_source_begin(g,&sio,D8SV_CURRENT);while(rc==D8SV_MORE)rc=d8cb_source_step();CHECK(rc==D8SV_CHANGED);end();
 retained(D8SV_CURRENT,1);nor[0x97000]^=1;rc=proposal(D8SV_CURRENT);CHECK(rc==D8SV_CHANGED||rc==D8SV_UNSUPPORTED);end();
 for(unsigned a=0;a<5;a++){retained(D8SV_CURRENT,1);CHECK(proposal(D8SV_CURRENT)==D8SV_COMPLETE&&d8cb_seal(g)==D8CB_OK);d8mp_result result;CHECK(d8mp_validate(g,&result)==D8MP_OK);memset(&main_migration_workspace(g)->stage,0xa5,sizeof(d8p1_stage_workspace));uint32_t before=d8p1_crc32(&main_migration_workspace(g)->stage,sizeof(d8p1_stage_workspace));if(a==0)d8_capture_store_changed();else if(a==1)usb.config=0;else if(a==2)usb.resets++;else if(a==3)fm1_ms+=EDC_TIMEOUT+1;else flash_ok=0;CHECK(!d8cb_metadata_valid(g));CHECK(before==d8p1_crc32(&main_migration_workspace(g)->stage,sizeof(d8p1_stage_workspace)));end();}
 retained(D8SV_CURRENT,1);CHECK(proposal(D8SV_CURRENT)==D8SV_COMPLETE&&d8cb_seal(g)==D8CB_OK);uint32_t old=g;CHECK(d8mp_end(g)==D8MP_OK);uint32_t newer;CHECK(d8mp_begin(&newer)==D8MP_OK);CHECK(!d8cb_metadata_valid(old));d8cb_cancel();CHECK(migration_owner==newer);CHECK(d8mp_end(newer)==D8MP_OK);
 retained(D8SV_CURRENT,1);uint32_t before=d8p1_crc32(&main_workspace,sizeof main_workspace);CHECK(d8cb_begin((uint32_t*)&main_workspace)==D8CB_BAD);CHECK(d8cb_begin(&ed_capture.token)==D8CB_BAD);uint32_t epoch=d8_capture_change.epoch,resets=usb.resets,now=fm1_ms;CHECK(d8cb_begin(&d8_capture_change.epoch)==D8CB_BAD);CHECK(d8cb_begin(&usb.resets)==D8CB_BAD);CHECK(d8cb_begin(&fm1_ms)==D8CB_BAD);CHECK(epoch==d8_capture_change.epoch&&resets==usb.resets&&now==fm1_ms&&!migration_owner);CHECK(before==d8p1_crc32(&main_workspace,sizeof main_workspace));end();
 retained(D8SV_CURRENT,1);CHECK(proposal(D8SV_CURRENT)==D8SV_COMPLETE&&d8cb_seal(g)==D8CB_OK);trk[7].p[P_LEVEL]^=1;CHECK(d8cb_metadata_valid(g));puts("LIMITATION: unobserved RAM edit after seal requires coordinator edit exclusion; metadata is not permission");end();
 printf("Native migration capture binding: %u checks, %u failures; prior17-role identity; no device/production authority\n",checks,failures);return failures!=0;}
